import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillFacebook, AiFillInstagram } from "react-icons/ai";
import Image from "next/image";
import pp from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.jpg";
import web2 from "../public/web2.jpg";
import web3 from "../public/web3.jpg";
import web4 from "../public/web4.jpg";
import web5 from "../public/web5.jpg";
import web6 from "../public/web6.jpg";
import { useState } from "react";

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);

    return (
        <>
            <div className={darkMode ? "dark" : ""}>
                <Head>
                    <title>Portfolio</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
                    <section className="min-h-screen">
                        <nav className="py-10 mb-12 flex justify-between">
                            <h1 className="text-xl font-burtons dark:text-white">dipeshparajuli</h1>
                            <ul className="flex items-center">
                                <li>
                                    <BsFillMoonStarsFill
                                        onClick={() => setDarkMode(!darkMode)}
                                        className="cursor-pointer text-xl dark:text-white"
                                    />
                                </li>
                                <li>
                                    <a
                                        className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 resume-link"
                                        href="#">
                                        Resume
                                    </a>
                                </li>
                            </ul>
                        </nav>
                        <div className="text-center p-10 py-10">
                            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
                                Dipesh Parajuli
                            </h2>
                            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
                                Developer and Designer
                            </h3>
                            <p className="dark:text-gray-200 text-medium py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
                                I love to work with people and make things that people love.
                                Freelancer providing services for programming and design content
                                needs. Join me down below and let&apos;s get connected!
                            </p>
                        </div>
                        <div className="dark:text-white text-5xl flex justify-center gap-16 py-3 text-gray-600">
                            <AiFillLinkedin />
                            <AiFillFacebook />
                            <AiFillInstagram />
                        </div>
                        <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
                            <Image src={pp} alt="profile" layout="fill" objectFit="cover" />
                        </div>
                    </section>

                    <section>
                        <div className="text-center p-10 py-10">
                            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
                            <p className="text-medium py-2 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200">
                                Lorem ipsum dolor sit amet consectetur{" "}
                                <span className="text-teal-500">adipisicing</span> elit. Autem fugit
                                odio cum. Enim, voluptates. Asperiores, quas. Eveniet eos at{" "}
                                <span className="text-teal-500">doloremque</span> in ad odio
                                molestiae quae, quibusdam obcaecati esse quaerat. Maxime.
                            </p>
                            <p className="text-medium py-2 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200">
                                Lorem ipsum dolor sit amet consectetur{" "}
                                <span className="text-teal-500">adipisicing</span> elit. Dolore
                                quibusdam quaerat esse nulla magnam{" "}
                                <span className="text-teal-500">doloremque</span> temporibus dolorem
                                laboriosam, nisi quis.
                            </p>
                        </div>
                        <div className="lg:flex gap-10">
                            <div className="text-center shadow-lg shadow-slate-400 p-10 rounded-xl my-10 dark:bg-white flex-1 hover:-translate-y-3 transition-all ease-in-out 0.5s">
                                <Image
                                    className="mx-auto"
                                    src={design}
                                    alt="design"
                                    width={100}
                                    height={100}
                                />
                                <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
                                <p className="py-2">
                                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam
                                    in, quidem quam exercitationem distinctio repudiandae.
                                </p>
                                <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white py-2 px-4 rounded-md mt-8 mb-4 view-btn">
                                    View Details
                                </button>
                            </div>
                            <div className="text-center shadow-lg shadow-slate-400 p-10 rounded-xl my-10 dark:bg-white flex-1 hover:-translate-y-3 transition-all ease-in-out 0.5s">
                                <Image
                                    className="mx-auto"
                                    src={code}
                                    alt="design"
                                    width={100}
                                    height={100}
                                />
                                <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
                                <p className="py-2">
                                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam
                                    in, quidem quam exercitationem distinctio repudiandae.
                                </p>
                                <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white py-2 px-4 rounded-md mt-8 mb-4 view-btn">
                                    View Details
                                </button>
                            </div>
                            <div className="text-center shadow-lg shadow-slate-400 p-10 rounded-xl my-10 dark:bg-white flex-1 hover:-translate-y-3 transition-all ease-in-out 0.5s">
                                <Image
                                    className="mx-auto"
                                    src={consulting}
                                    alt="design"
                                    width={100}
                                    height={100}
                                />
                                <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
                                <p className="py-2">
                                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam
                                    in, quidem quam exercitationem distinctio repudiandae.
                                </p>
                                <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white py-2 px-4 rounded-md mt-8 mb-4 view-btn">
                                    View Details
                                </button>
                            </div>
                        </div>
                    </section>

                    <section>
                        <div className="text-center p-10 py-10">
                            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
                            <p className="text-medium py-2 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-lg mx-auto">
                                Lorem ipsum dolor sit amet consectetur{" "}
                                <span className="text-teal-500">adipisicing</span> elit. Autem fugit
                                odio cum. Enim, voluptates. Asperiores, quas. Eveniet eos at{" "}
                                <span className="text-teal-500">doloremque</span> in ad odio
                                molestiae quae, quibusdam obcaecati esse quaerat. Maxime.
                            </p>
                            <p className="text-medium py-2 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-lg mx-auto">
                                Lorem ipsum dolor sit amet consectetur{" "}
                                <span className="text-teal-500">adipisicing</span> elit. Dolore
                                quibusdam quaerat esse nulla magnam{" "}
                                <span className="text-teal-500">doloremque</span> temporibus dolorem
                                laboriosam, nisi quis.
                            </p>
                        </div>
                        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                            <div className="basis-1/3 flex-1">
                                <Image
                                    src={web1}
                                    alt="web-pic"
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                />
                            </div>
                            <div className="basis-1/3 flex-1">
                                <Image
                                    src={web2}
                                    loading="lazy"
                                    alt="web-pic"
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                />
                            </div>
                            <div className="basis-1/3 flex-1">
                                <Image
                                    src={web3}
                                    alt="web-pic"
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                />
                            </div>
                            <div className="basis-1/3 flex-1">
                                <Image
                                    src={web4}
                                    alt="web-pic"
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                />
                            </div>
                            <div className="basis-1/3 flex-1">
                                <Image
                                    src={web5}
                                    alt="web-pic"
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                />
                            </div>
                            <div className="basis-1/3 flex-1">
                                <Image
                                    src={web6}
                                    alt="web-pic"
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                />
                            </div>
                        </div>
                    </section>
                </main>
            </div>
        </>
    );
}
